module.exports = (req, res) => {
  res.status(200).json({
    contratos: [
      {
        cpf: "123.456.789-01",
        nome: "João da Silva",
        numero_contrato: "CDT-2025-0001",
        data_inicio_contrato: "2025-01-15",
        valor_financiado: 12000.0,
        valor_parcela: 500.0,
        quantidade_parcelas: 24,
        data_vencimento_proxima_parcela: "2025-10-15",
        data_pagamento_ultima_parcela: "2025-09-15",
        status: "Ativo",
        ticket: 101,
        descricao_ticket:
          "Como eu pago o Crédito do Trabalhador se estou afastado do meu emprego?",
      },
      {
        cpf: "456.789.123-02",
        nome: "Maria Oliveira",
        numero_contrato: "CDT-2025-0002",
        data_inicio_contrato: "2025-02-01",
        valor_financiado: 8000.0,
        valor_parcela: 666.67,
        quantidade_parcelas: 12,
        data_vencimento_proxima_parcela: "2025-09-20",
        data_pagamento_ultima_parcela: "2025-09-10",
        status: "Em reembolso",
        ticket: 102,
        descricao_ticket:
          "Qual é o prazo para receber o reembolso de um pagamento duplicado do Crédito do Trabalhador?",
      },
      {
        cpf: "789.123.456-03",
        nome: "Carlos Pereira",
        numero_contrato: "CDT-2025-0003",
        data_inicio_contrato: "2025-03-10",
        valor_financiado: 6000.0,
        valor_parcela: 500.0,
        quantidade_parcelas: 12,
        data_vencimento_proxima_parcela: "2025-09-30",
        data_pagamento_ultima_parcela: "2025-09-01",
        status: "Conciliação pendente",
        ticket: 103,
        descricao_ticket:
          "Por que o desconto da parcela do Crédito do Trabalhador apareceu no meu salário e também na minha conta PicPay?",
      },
      {
        cpf: "147.258.369-04",
        nome: "Fernanda Costa",
        numero_contrato: "CDT-2025-0004",
        data_inicio_contrato: "2025-04-05",
        valor_financiado: 10000.0,
        valor_parcela: 416.67,
        quantidade_parcelas: 24,
        data_vencimento_proxima_parcela: "2025-09-25",
        data_pagamento_ultima_parcela: "2025-09-05",
        status: "Divergência de dados",
        ticket: 104,
        descricao_ticket:
          "Por que as informações do meu Crédito do Trabalhador são diferentes entre o PicPay e o app da Carteira de Trabalho Digital?",
      },
      {
        cpf: "258.369.147-05",
        nome: "Rafael Santos",
        numero_contrato: "CDT-2025-0005",
        data_inicio_contrato: "2025-05-12",
        valor_financiado: 15000.0,
        valor_parcela: 1250.0,
        quantidade_parcelas: 12,
        data_vencimento_proxima_parcela: "2025-10-12",
        data_pagamento_ultima_parcela: "2025-09-12",
        status: "Solicitação de antecipação",
        ticket: 105,
        descricao_ticket: "Como antecipar parcelas do Crédito do Trabalhador?",
      },
      {
        cpf: "369.147.258-06",
        nome: "Juliana Lima",
        numero_contrato: "CDT-2025-0006",
        data_inicio_contrato: "2025-06-01",
        valor_financiado: 9000.0,
        valor_parcela: 750.0,
        quantidade_parcelas: 12,
        data_vencimento_proxima_parcela: "2025-09-28",
        data_pagamento_ultima_parcela: "2025-08-28",
        status: "Solicitação em análise",
        ticket: 106,
        descricao_ticket:
          "Caso meu contrato de trabalho seja encerrado é possível antecipar as parcelas do Crédito do Trabalhador?",
      },
      {
        cpf: "951.753.159-07",
        nome: "Paulo Henrique",
        numero_contrato: "CDT-2025-0007",
        data_inicio_contrato: "2025-07-15",
        valor_financiado: 7000.0,
        valor_parcela: 583.33,
        quantidade_parcelas: 12,
        data_vencimento_proxima_parcela: "2025-09-15",
        data_pagamento_ultima_parcela: null,
        status: "Parcela em atraso",
        ticket: 107,
        descricao_ticket:
          "Por que a minha parcela do Crédito do Trabalhador aparece em atraso?",
      },
      {
        cpf: "753.159.951-08",
        nome: "Camila Rocha",
        numero_contrato: "CDT-2025-0008",
        data_inicio_contrato: "2025-08-01",
        valor_financiado: 11000.0,
        valor_parcela: 916.67,
        quantidade_parcelas: 12,
        data_vencimento_proxima_parcela: "2025-09-20",
        data_pagamento_ultima_parcela: "2025-08-20",
        status: "Conciliação após quitação",
        ticket: 108,
        descricao_ticket:
          "Por que tive desconto em salário ou débito em conta mesmo depois de antecipar, pagar uma parcela ou quitar todo meu contrato de Crédito do Trabalhador?",
      },
    ],
  });
};
